node_env: "development"
url_db: "postgres://pg:123456@localhost:5432/cost_service_db?sslmode=disable"
name_service: "CostService"
port_grpc: 50056
host_grpc: "localhost"
interval_check: "20s"
timeout_check: "15s"
